version: "3.2"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - e2e

    mongo:
        image: mongo:4
        ports:
            - "27017:27017"
        networks:
            - e2e
        tmpfs:
            - /data/db

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        ports:
            - "9200:9200"
        networks:
            - e2e
        environment:
            - discovery.type=single-node
            - action.auto_create_index=false
        tmpfs:
            - /usr/share/elasticsearch/data

    superdesk:
        build: .
        ports:
            - "5000:5000"
            - "5100:5100"
        networks:
            - e2e
        environment:
            - REDIS_URL=redis://redis:6379/1
            - ELASTICSEARCH_URL=http://elastic:9200
            - MONGO_URI=mongodb://mongo/superdesk_e2e
            - ARCHIVED_URI=mongodb://mongo/superdesk_e2e_archived
            - LEGAL_ARCHIVE_URI=mongodb://mongo/superdesk_e2e_legal_archive
            - PUBLICAPI_MONGO_URI=mongodb://mongo/publicapi_e2e
            - CONTENTAPI_MONGO_URI=mongodb://mongo/contentapi_e2e
            - WEB_WORKERS=2
            - WEB_TIMEOUT=30
            - WEB_LOG_LEVEL=info
networks:
    e2e:
        driver: bridge
