version: "2.4"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

    elastic:
        image: elasticsearch:7.7.0
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data

    superdesk:
        build: .
        ports:
            - "5000:5000"
            - "5100:5100"
        links:
            - redis
            - mongo
            - elastic
        environment:
            - REDIS_URL=redis://redis:6379/1
            - ELASTICSEARCH_URL=http://elastic:9200
            - MONGO_URI=mongodb://mongo/superdesk_e2e
            - ARCHIVED_URI=mongodb://mongo/superdesk_e2e_archived
            - LEGAL_ARCHIVE_URI=mongodb://mongo/superdesk_e2e_legal_archive
            - PUBLICAPI_MONGO_URI=mongodb://mongo/publicapi_e2e
            - CONTENTAPI_MONGO_URI=mongodb://mongo/contentapi_e2e
            - WEB_WORKERS=2
            - WEB_TIMEOUT=30
            - WEB_LOG_LEVEL=info
            - SENTRY_DSN
