name: "CI"

on:
  [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # avoid file watch limit error
    - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - run: npm ci
    - run: npm run test

  e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite: [a, b]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'


    - name: Start e2e server
      run: |
        docker-compose pull
        docker-compose build
        docker-compose up -d
      working-directory: e2e/server

    - name: Build client
      run: npm install && npm run build && npm run specs--compile && npm run start-client-server
      working-directory: e2e/client
    
    - name: Protractor
      run: ./node_modules/.bin/protractor protractor.conf.js --suite=${{ matrix.suite }}
      env:
        TRAVIS: ci
        SCREENSHOTS_DIR: /tmp
      working-directory: e2e/client

    - name: Upload screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots-e2e-${{ matrix.suite }}
        path: /tmp/*.png
